### ISSUE TITLE
Fuzzy Finder does not steal focus from command palette (or vice-versa)

### ISSUE THREAD

**Issue by Ajedi32** [atom/fuzzy-finder#350] opened 2018-05-29 16:34 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I invoke Atom's built-in Command Pallet plugin via it's default keyboard shortcut, then do the same with the Fuzzy Finder while the command pallet is still open, the Fuzzy Finder does not steal focus from the Command Pallet. Rather, focus returns to the main editor.

This means that if I accidentally open the command pallet, then open the Fuzzy Finder and start typing a file name, that name will end up in my editor's buffer, not in the Fuzzy Finder. This is extremely annoying, and not expected behavior.

### Steps to Reproduce

1. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> to open the command pallete
2. Press <kbd>Ctrl</kbd>+<kbd>T</kbd> to open the fuzzy finder
3. Enter the name of a file in the current project

**Expected behavior:** The file whose name you just entered appears in the Fuzzy Finder.

**Actual behavior:** The text you just entered is added to the buffer of the file you currently have open in Atom.

**Reproduces how often:** Always.

### Versions

Atom: 1.27.1
Electron: 1.7.15
Chrome: 58.0.3029.110
Node: 7.9.0
fuzzy-finder: 1.8.1
command-palette: 0.43.5
OS: Windows 10

**Comment by rsese** [comment] 2018-05-29 21:51
Thanks for the report @Ajedi32 :v:

> Given this issue seems to involve the command pallete as well, should I file a similar issue on that repository as well?

That won't be necessary, this has already been reported - I'll go ahead and close as a duplicate of https://github.com/atom/atom/issues/14325 and you can subscribe there if you'e like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-29 21:51 UTC
