### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'path'

### ISSUE THREAD

**Issue by bvjebin** [atom/fuzzy-finder#201] opened 2016-04-28 18:13 UTC
[Enter steps to reproduce below:]

1. Ctrl+p

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.3
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/jebin/support/practice/projects/bot_transactions'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/jebin/support/practice/projects/bot_transactions'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  4x -1:58.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:45.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:04.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.9
atom-beautify, v0.29.7
atom-ternjs, v0.14.1
autocomplete-python, v1.7.2
browser-plus, v0.0.60
emmet, v2.4.3
language-elixir, v0.12.3
linter, v1.11.4
project-manager, v2.9.7
python-indent, v0.4.3
python-tools, v0.6.7
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-04-28 23:14
This is a duplicate of #196. Please subscribe there for updates.

**Closed by lee-dohm** 2016-04-28 23:14 UTC
