### ISSUE TITLE
Fuzzy Finder perpetually "reindexing project"

### ISSUE THREAD

**Issue by sirianni** [atom/fuzzy-finder#162] opened 2015-12-11 00:54 UTC
In one of my atom workspaces, the Fuzzy Finder always shows "reindexing project".  This seems to have occurred after a recent atom upgrade.  This project does not have an exorbitant number of files (<1000).

**Comment by lee-dohm** [comment] 2015-12-11 02:40
This is a duplicate of https://github.com/atom/fuzzy-finder/issues/88. Please subscribe to that issue for updates.

**Closed by lee-dohm** 2015-12-11 02:40 UTC
