### ISSUE TITLE
I need mixed file-finder & buffer-finder, like Sublime Text

### ISSUE THREAD

**Issue by beviz** [atom/fuzzy-finder#342] opened 2018-02-27 09:07 UTC
Just remember one shortcut, I can search files with keywords or select recent(sorted) opened files. just like Sublime Text's `Command + P`.

That's why every time I try to use the Atom, I go back to using Sublime Text.

**Comment by scottwio** [comment] 2018-03-06 21:34
vs-code has the same thing. If you have no text in the search input it shows recently opened files.

**Comment by beviz** [comment] 2018-03-14 09:57
@scottwio thx for reply.

> If you have no text in the search input it shows recently opened files.

In my environment, Atom also shows recently opened files, but after a few seconds("reindexing" text at top gone), it only keeps last one recent file. maybe it's reordered?

**Comment by lee-dohm** [comment] 2018-04-21 18:40
Thanks for reaching out!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/214. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-04-21 18:40 UTC
