### ISSUE TITLE
Case insensitive find doesn't work

### ISSUE THREAD

**Issue by borishere** [atom/fuzzy-finder#346] opened 2018-04-30 16:37 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Case insensitive find doesn't work for Russian language.

![8](https://user-images.githubusercontent.com/4622497/39438539-2a3d02ee-4cad-11e8-9c6d-94da0611c0d6.gif)

### Steps to Reproduce

1. Gif explains all

**Reproduces how often:** 100%

### Versions

Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.14
git 2.13.0.windows.1
visual studio

Windows 10 Pro

**Comment by rsese** [comment] 2018-04-30 23:57
Thanks for contributing!

I think this is a duplicate of https://github.com/atom/superstring/issues/56 which is fixed as of 1.27.0-beta0.  If things aren't fixed you in that version let me know.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-30 23:57 UTC
