### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, lstat  W:/dropbox-nr4jlc 

### ISSUE THREAD

**Issue by taa1** [atom/fuzzy-finder#300] opened 2017-05-24 21:14 UTC
Enter steps to reproduce:  1. All I did was launch Atom. It tried to open the last file I was working on. Drive W: in the error is a mapped network drive using SFTP Net Drive software.

... 2. ... **Atom**: 1.17.0 x64 **Electron**: 1.3.15 **OS**: Microsoft Windows 7 Home Premium  **Thrown From**:  fuzzy-finder  https://github.com/atom/fuzzy-finder  package 1.5.6 ### Stack Trace Uncaught Error: EISDIR: illegal operation on a directory, lstat  W: dropbox-nr4jlc      At fs.js:982 Error: EISDIR: illegal operation on a directory, lstat  W: dropbox-nr4jlc   at Error  native   at fs.lstatSync  fs.js:982:18   at Object.fs.lstatSync  ELECTRON_ASAR.js:239:16   at Proxy.realpathSync  fs.js:1657:19   at Proxy.fs.realpathSync  ELECTRON_ASAR.js:316:29   at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:21:1  at Array.map  native   at Object.startTask  ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:19:1   at Object.startLoadPathsTask  ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/fuzzy-finder/lib/main.js:119:1   at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/fuzzy-finder/lib/main.js:33:1  at _combinedTickCallback  internal/process/next_tick.js:67:7   at process._tickCallback  internal/process/next_tick.js:98:9      ### Commands         ### Non-Core Packages     editing-diff 0.2.1  language-markdown 0.22.0  markdown-folder 0.5.0  markdown-preview-plus 2.4.9  markdown-scroll-sync 2.1.2  markdown-writer 2.6.5  tool-bar-markdown-writer 0.2.0

**Comment by rsese** [comment] 2017-05-26 20:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/290. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-26 20:59 UTC
