### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/alex/nuclide:'

### ISSUE THREAD

**Issue by alexrqs** [atom/fuzzy-finder#247] opened 2016-07-31 17:04 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/alex/nuclide:'

```
At fs.js:887

Error: ENOENT: no such file or directory, lstat '/home/alex/nuclide:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:04.3.0 settings-view:open (atom-text-editor.editor.is-focused)
  3x -0:50.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:48.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:38 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-always.seti-icons.seti-roboto.seti-animate.theme-monokai-seti.theme-seti-ui)
     -0:01.1.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "takana-atom",
      "tree-view"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
atom-jade, v0.3.0
atom-pair, v2.0.10
autocomplete-paths, v1.0.2
django-atom, v0.2.4
emmet, v2.4.3
language-aspx, v0.4.0
language-ejs, v0.2.0
language-haml, v0.24.0
language-javascript-jsx, v0.3.7
language-liquid, v0.5.1
language-python-django-templates, v0.1.0
linter, v1.11.14
monokai-seti, v0.7.0
nuclide, v0.158.0
pigments, v0.31.2
seti-ui, v1.3.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-07-31 21:41
This is a duplicate of #233 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-31 21:41 UTC
