### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, lstat '/\san\dept\is'

### ISSUE THREAD

**Issue by DJHig** [atom/fuzzy-finder#286] opened 2017-04-12 17:20 UTC
I get this error when I open Atom. My projects are stored on a SAN share under this folder.

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.4.1

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, lstat '\\san\dept\is'

```
At fs.js:982

Error: EISDIR: illegal operation on a directory, lstat '\\san\dept\is'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Object.realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:117:39)
    at /app.asar/node_modules/fuzzy-finder/lib/main.js:31:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-grails 1.0.1 
language-groovy 0.6.0 
```

**Comment by Arcanemagus** [comment] 2018-03-15 05:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/290. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-15 05:55 UTC
