### ISSUE TITLE
Uncaught Error: Cannot find module '/usr/lib/atom/node_modules/@atom/fuzzy-native/build/fuzzy-nat...

### ISSUE THREAD

**Issue by acodispo** [atom/fuzzy-finder#389] opened 2019-05-15 21:07 UTC
[Enter steps to reproduce:]

1. load Atom
2. open Fuzzy Finder

**Atom**: 1.37.0 x64
**Electron**: 4.1.4
**OS**: linux 5.1.2-arch1-1-ARCH
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.13.1

### Stack Trace

Uncaught Error: Cannot find module '/usr/lib/atom/node_modules/@atom/fuzzy-native/build/fuzzy-native/v0.7.0/node-v69-linux-x64/fuzzy-native.node'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module '/usr/lib/atom/node_modules/@atom/fuzzy-native/build/fuzzy-native/v0.7.0/node-v69-linux-x64/fuzzy-native.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:283:28)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/usr/lib/atom/node_modules/@atom/fuzzy-native/lib/main.js:16:18)
    at Object.<anonymous> (/usr/lib/atom/node_modules/@atom/fuzzy-native/lib/main.js:18:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/usr/lib/atom/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:6:21)
    at Object.<anonymous> (/usr/lib/atom/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:525:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/usr/lib/atom/node_modules/fuzzy-finder/lib/project-view.js:4:25)
    at Object.<anonymous> (/usr/lib/atom/node_modules/fuzzy-finder/lib/project-view.js:193:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
```

### Commands

```
     -0:12 fuzzy-finder:toggle-file-finder (input.hidden-input)
  2x -0:09.9.0 core:backspace (input.hidden-input)
     -0:09.2.0 editor:consolidate-selections (input.hidden-input)
     -0:09.2.0 core:cancel (input.hidden-input)
     -0:09.0 editor:consolidate-selections (input.hidden-input)
     -0:09.0 core:cancel (input.hidden-input)
     -0:07.3.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-ungit 0.8.0 
docblockr 0.13.7 
git-blame 1.8.0 
hyperclick 0.0.0 
ide-css 0.3.2 
ide-html 0.5.0 
ide-php 0.7.18 
jQuery 1.2.6 
js-hyperclick 1.13.3 
language-diff 0.7.0 
language-fish-shell 1.1.0 
language-ini 1.20.0 
language-markdown 0.29.0 
language-mjml 2.0.1 
markdown-mindmap 0.6.1 
mjml-preview 2.0.1 
php-cs-fixer 4.1.1 
php-hyperclick 1.2.1 
split-diff 1.6.0 
todo-show 2.3.2 
wordcount 3.1.0 
```

**Comment by 50Wliu** [comment] 2019-05-15 21:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #388. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2019-05-15 21:15 UTC

**Comment by johnc219** [comment] 2019-05-31 17:50
Anyone who's still running into this: the Arch linux package has been updated.
```
sudo pacman -Sy atom
```
should do the trick.

**Comment by erayerdin** [comment] 2019-06-10 22:21
Having the same issue in Manjaro's official package.

**Comment by 50Wliu** [comment] 2019-06-11 02:25
No, I highly recommend that you **do not** use the Snap package. The Atom team does not officially support the Snap package and you run the risk of running into issues that are not present on the official distributions.

Install Atom from https://atom.io instead.
