### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/bsemene/atom:'

### ISSUE THREAD

**Issue by Sabbasth** [atom/fuzzy-finder#200] opened 2016-04-28 08:24 UTC
1. Fresh install
2. Open folder (Cmd-o)
Note: The opened folder isn't in the path: /home/bsemene/atom
3. Cmd-t

**Atom Version**: 1.7.2
**System**: Linux Mint
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/bsemene/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/bsemene/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -4:02.3.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -4:01.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:01.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:57.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:57.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:57.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -3:56.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:54.6.0 core:delete (atom-text-editor.editor.is-focused)
  2x -3:51 core:undo (atom-text-editor.editor.is-focused)
     -3:48.5.0 core:redo (atom-text-editor.editor.is-focused)
     -3:47.2.0 core:undo (atom-text-editor.editor.is-focused)
     -2:05.9.0 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
     -2:02.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:02.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:15.5.0 editor:checkout-head-revision (atom-text-editor.editor.is-focused)
     -0:00.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

Duplicate of: #118

**Comment by lee-dohm** [comment] 2016-04-28 23:13
Duplicate of #196.

**Closed by lee-dohm** 2016-04-28 23:13 UTC
