### ISSUE TITLE
New file in project folder is not searchable

### ISSUE THREAD

**Issue by dinusubba** [atom/fuzzy-finder#175] opened 2016-02-18 04:40 UTC
_From @dinusubba on February 17, 2016 13:7_

When a new file is created in a project folder either by copy paste or using save as option. It is not searchable immediately using Command+T on Mac.
After a brief moment (couple of minutes) it started appearing in the search results.
<img width="928" alt="screen shot 2016-02-17 at 6 35 50 pm" src="https://cloud.githubusercontent.com/assets/5587801/13110343/7355255a-d5a5-11e5-9df5-250ceb42fb36.png">

_Copied from original issue: atom/atom#10859_

**Comment by dinusubba** [comment] 2016-02-18 04:40
_From @50Wliu on February 17, 2016 20:33_

@dinusubba Can you please move this over to the [atom/fuzzy-finder](https://github.com/atom/fuzzy-finder) repository?  Thanks!

**Comment by dinusubba** [comment] 2016-02-18 04:40
Sure I will move this

**Comment by abe33** [comment] 2016-02-29 10:18
I think the problem is not limited to new files: 

![fuzzy-finder](https://cloud.githubusercontent.com/assets/247140/13391595/994910f8-ded5-11e5-9429-296e0bd2de13.gif)

In the gif above I have a file (which is not new), if I open the fuzzy finder it's empty, on the other opened file it is not. Then I open a third file and then all the three files opens a fuzzy finder with the proper entries. And as soon as I remove the third file, the second one starts again to open an empty fuzzy finder.

**Comment by lee-dohm** [comment] 2016-02-29 22:19
I haven't been able to reproduce this using Atom v1.5.3 on Mac OS X 10.11.3. @abe33 do you have any hints?

**Comment by abe33** [comment] 2016-03-03 13:16
I could reproduce that issue on 1.7.0-dev-2bdf4be in safe mode, both with and without the alternate scoring mode. 

I somehow found way to reproduce that ever time:

- Split panes and leave them both empty
- Create a new file in the tree-view, it should open it in one of the panes
- Select the empty pane and trigger the fuzzy finder, the list is empty
- Select the pane with the new file and trigger the fuzzy finder, the list has the proper content

I haven't looked at the sources yet to see if I could spot where the issue comes from though.

**Comment by lee-dohm** [comment] 2016-03-03 17:40
Awesome @abe33, thanks! I'll try to repro this later today.

**Comment by 50Wliu** [comment] 2016-07-15 00:52
Similar enough to #30 that I'm going to close this issue in favor of that one.

**Closed by 50Wliu** 2016-07-15 00:52 UTC
Labels: atom, bug
