### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat 'C:/Users\pc'

### ISSUE THREAD

**Issue by tipiwiny** [atom/fuzzy-finder#310] opened 2017-07-25 08:36 UTC
[Enter steps to reproduce:]

1. .Error starting Atom

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Windows 10
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.8

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'C:\Users\pc'

```
At fs.js:982

Error: EPERM: operation not permitted, lstat 'C:\Users\pc'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Proxy.realpathSync (fs.js:1657:19)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:21:27
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:19:52)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/main.js:119:45)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/main.js:33:30
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-node-debugger undefined 
busy-signal 1.3.0 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.2 
linter-eslint 8.1.5 
linter-jshint 3.0.3 
linter-ui-default 1.2.2 
node-debug 0.1.7 
react 0.16.2 
```

**Comment by Arcanemagus** [comment] 2018-03-15 05:53
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/289. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-15 05:53 UTC
