### ISSUE TITLE
Uncaught Error: EINVAL: invalid argument, lstat '/\NetworkDrive\users'

### ISSUE THREAD

**Issue by taserian** [atom/fuzzy-finder#277] opened 2017-02-24 19:27 UTC
[Enter steps to reproduce:]

1. Attempted to open a file on a Windows network drive, where I don't have permissions on all of the folders in the path.

Anonymized example:
- \\\\NetworkDrive  (no permissions)
- \\\\NetworkDrive\users (no permissions)
- \\\\NetworkDrive\users\taserian (allowed to read/write to this folder)

I also notice that the error message copied over to GitHub as: 

`lstat '/\NetworkDrive\users'`

but in the error window in Atom, I see:

`lstat '\\NetworkDrive\users'`

Could it be an escaping issue?

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.4.1

### Stack Trace

Uncaught Error: EINVAL: invalid argument, lstat '\\s4000fs01\users\'

```
At fs.js:982

Error: EINVAL: invalid argument, lstat '\\s4000fs01\users\'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at start (fs.js:1634:10)
    at Object.realpathSync (fs.js:1622:3)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:117:39)
    at /app.asar/node_modules/fuzzy-finder/lib/main.js:31:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-elixir 0.2.2 
atom-elixir-playground 0.1.0 
atom-ternjs 0.17.2 
auto-detect-indentation 1.3.0 
autocomplete-elixir 1.5.14 
autocomplete-modules 1.6.7 
autocomplete-python 1.8.57 
autoprefixer 3.6.1 
build-elixir 0.6.0 
color-picker 2.2.5 
custom-title 1.0.1 
docblockr 0.9.1 
editorconfig 2.2.2 
elixir-cmd 0.2.9 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.0.15 
git-plus 7.3.3 
git-projects 1.17.0 
git-time-machine 1.5.6 
highlight-selected 0.12.0 
imdone-atom 2.1.19 
language-elixir 0.17.0 
less-than-slash 0.16.0 
linter 1.11.23 
linter-elixir-credo 1.1.0 
linter-elixirc 1.2.0 
linter-eslint 8.1.2 
linter-flow 5.5.0 
linter-js-standard 3.9.0 
linter-jshint 3.0.2 
linter-perl 0.8.0 
linter-perl-remote 0.8.1 
minimap 4.26.8 
minimap-pigments 0.2.2 
nuclide 0.207.0 
open-recent 5.0.0 
phoenix-elixir-snippets 0.4.0 
pigments 0.39.0 
project-manager 3.3.3 
Quick-JavaScript 2.2.0 
react 0.16.2 
script 3.14.1 
seti-icons 1.3.4 
simple-drag-drop-text 0.3.4 
sync-settings 0.8.1 
term3 0.22.1 
todo-show 1.11.0 
tool-bar 1.0.1 
turbo-javascript 1.4.0 
```

**Comment by Arcanemagus** [comment] 2018-03-15 06:01
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/324. It looks like the fix to this is required to be done at the Node.js level, and should be included in Node.js 9.3.0. You may want to subscribe to that issue for updates on when this is resolved.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-15 06:01 UTC
