### ISSUE TITLE
Unable to find some files

### ISSUE THREAD

**Issue by umpirsky** [atom/fuzzy-finder#163] opened 2015-12-15 18:30 UTC
I have this issue with any [Symfony](http://symfony.com/) project.

Here is test on [Sylius](https://github.com/sylius/sylius/) example:

![-home-umpirsky-projects-sylius - atom_013](https://cloud.githubusercontent.com/assets/208957/11819540/bf4ec186-a360-11e5-9bba-caa2222bb4f8.png)

I tried to find `/home/umpirsky/Projects/Sylius/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php` by typing `symfony form`, but didn't see it in the result list.

Some files are found, some not.

config.cson:

```json
"*":
  "exception-reporting":
    userId: "2cc80772-6b4e-7190-4965-46a446a9a60d"
  welcome:
    showOnStartup: false
  core:
    projectHome: "/home/umpirsky/Projects"
    excludeVcsIgnoredPaths: false
    ignoredNames: [
      ".git"
      "app/cache"
      "app/logs"
    ]
  editor:
    invisibles: {}
    tabLength: 4
  "linter-php":
    executablePath: "/usr/bin/php"
  linter:
    lintOnFly: false
  "atom-autocomplete-php":
    binComposer: "composer"
  "atom-symfony2": {}
  docblockr: {}
  "fuzzy-finder": {}

```

If you need more information needed to reproduce, I will be happy to provide.

Also, I am ready to debug if someone can give me a hint.

**Comment by lee-dohm** [comment] 2015-12-16 01:23
* What you were searching for is not in the list at all? Or not at the top of the list?
* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting all instances of Atom and then starting it using the command `atom --safe`?

**Comment by umpirsky** [comment] 2015-12-16 07:31
@lee-dohm Thanks for the quick response.

* What I was searching for is not in the list at all.
* I am using Atom 1.3.1.
* I am running Ubuntu 15.10 with Unity desktop.
* Yes, I get same behavior in safe mode.

**Comment by umpirsky** [comment] 2015-12-16 18:04
@lee-dohm Can you reproduce it?

**Comment by jeancroy** [comment] 2015-12-17 14:15
In fuzzy finder options can you enable alternate scoring ?

>not in the list at all
The thing with fuzzy finder is that if a file cannot score in the top ~15 results it might has well not exist.

**Comment by umpirsky** [comment] 2015-12-17 14:58
@jeancroy Bravo, that was the issue! Thanks!

But still, I will not close this issue, because after enabling alternate scoring, here is the result:

![-home-umpirsky-projects-sylius - atom_025](https://cloud.githubusercontent.com/assets/208957/11872682/f54e2912-a4d6-11e5-88d2-0462833ae968.png)

As you can see, expected result shows up first in the result list. I guess it should be visible even with disabled alternate scoring.

**Comment by jeancroy** [comment] 2015-12-17 15:13
> I guess it should be visible even with disabled alternate scoring.

The thing is something fuzzy finder have to deal with ~100K files on large project, so it do not show every file, only top results.

Alternate scoring is an attempt to fix classic scoring. For example you see much less results with scattered isolated letters. It is behind a flag for development, but there's plan for it in not too distant future.

AFAIK this is solved.

**Comment by 50Wliu** [comment] 2015-12-17 16:41
Yeah, I'm closing this, since the alternate scoring method will soon be on by default.

**Closed by 50Wliu** 2015-12-17 16:41 UTC

**Comment by umpirsky** [comment] 2015-12-17 20:33
@jeancroy That is what I expected, to show top results.

> so it do not show every file, only top results.

`/home/umpirsky/Projects/Sylius/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php` is top result, right?

**Comment by 50Wliu** [comment] 2015-12-17 20:35
@umpirsky Yeah, but only using the new scoring method.  The old one has some problems with it which is why it's being phased out.

**Comment by jeancroy** [comment] 2015-12-17 23:00
Yeah, long path often 'accidentally' contain your query, so old method give them lower score. 
For that reason, it is not in top results.

New method instead try to find grouped characters to detect if a match is wanted or not, so it works better on long path and some other situations.

**Comment by umpirsky** [comment] 2015-12-18 07:45
@50Wliu @jeancroy OK, thanks for clarification guys.
