### ISSUE TITLE
Can't open multi file in search box

### ISSUE THREAD

**Issue by msadeghyan1996** [atom/fuzzy-finder#404] opened 2019-08-24 07:17 UTC
Hi. I search index.blade.php file and fuzzy find many file's for me and i want open two file in search list and i can't do it and i most open 1 of index.blade.php file and search file's again and open next file.

**Comment by rsese** [comment] 2019-08-26 09:03
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Additionally, I think I understand what you're asking about and I believe it's a duplicate of https://github.com/atom/fuzzy-finder/issues/70 so you can subscribe there if you'd like.

**Closed by rsese** 2019-08-26 09:03 UTC
