### ISSUE TITLE
Doesn't work at all. Cannot find module 'atom'

### ISSUE THREAD

**Issue by octoxan** [atom/fuzzy-finder#235] opened 2016-07-07 13:33 UTC
The console throws this error whenever I open up Atom:

`Cannot find module 'atom' Error: Cannot find module 'atom'`
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\xander\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js:12:19)
    at Object.<anonymous> (C:\Users\xander\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js:180:4)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (C:\Users\xander\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\xander\AppData\Local\atom\app-1.8.0\resources\app.asar\src\task-bootstrap.js:110:13)
    at Object.<anonymous> (C:\Users\xander\AppData\Local\atom\app-1.8.0\resources\app.asar\src\task-bootstrap.js:112:4)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (C:\Users\xander\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:2:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:425:26)
    at node.js:602:27
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)

Clicking `CTRL + P` brings up the thing that says "Indexing Project... 0" and it just stays at zero for forever.. meaning some other extensions never work.

**Comment by 50Wliu** [comment] 2016-07-15 00:49
Closing as a duplicate of #205 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-15 00:49 UTC
