### ISSUE TITLE
Atom crashed when "Preserve Last Search" option was first taken into use

### ISSUE THREAD

**Issue by kaskelotti** [atom/fuzzy-finder#102] opened 2015-05-19 22:29 UTC
For the first time I ticked the setting for "Preserve Last Search" and made a search, Atom hanged giving the usual option to wait for the editor to respond. After clicking the "Wait" button, Atom crashed.

After the editor restart, everything seems to work fine.

As a programmer, my first hunch is of course that there's a null pointer exception as there was no previously preserved search in this case.

Version in use is **0.85.0**

**Comment by lee-dohm** [comment] 2015-05-20 01:44
Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

I can't reproduce the issue using Atom v0.201.0-ba98013 on Mac OS X 10.10.3.

**Comment by kaskelotti** [comment] 2015-05-20 07:32
Atom is version **0.199.0** running on **Windows**.

Unable to reproduce using the safe mode. Are there logs available somewhere?

**Comment by lee-dohm** [comment] 2015-05-20 15:40
If it isn't reproducing using Safe Mode, then it is almost assuredly a third-party package causing the problem.

**Comment by kaskelotti** [comment] 2015-05-20 17:32
Apparently there's no way to reproduce this or get anymore information at this point. I vote for closing.

**Comment by mnquintana** [comment] 2015-05-20 17:56
Thanks for the updates @kaskelotti! I'm gonna close this. If you do find the offending package you can open an issue on their repo.

**Closed by mnquintana** 2015-05-20 17:56 UTC
Labels: more-information-needed, needs-reproduction
