### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Library/Group Containers/G69SCX94XU.d...

### ISSUE THREAD

**Issue by HsounaZinoubi** [atom/fuzzy-finder#278] opened 2017-02-27 10:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.4.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/hsouna/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/Volumes/45.62.213.122'

```
At fs.js:982

Error: ENOENT: no such file or directory, lstat '/Users/hsouna/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/Volumes/45.62.213.122'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Object.realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:117:39)
    at /app.asar/node_modules/fuzzy-finder/lib/main.js:31:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-02-27 18:09
Hmmm, looks similar to issues like https://github.com/atom/fuzzy-finder/issues/255 and https://github.com/atom/fuzzy-finder/issues/253 - can you reproduce in safe mode (`atom --safe`)?

**Comment by rsese** [comment] 2017-03-02 23:57
Also if you can share what you were doing at the time of the error, that would be helpful as well.

**Comment by HsounaZinoubi** [comment] 2017-03-03 21:31
error occur when opening php file from "Mountain Duck" app mounted sftp Volume in macOS Sierra

**Comment by Arcanemagus** [comment] 2018-03-15 07:15
Thanks for taking the time to contribute!

I'm marking this is a duplicate of https://github.com/atom/fuzzy-finder/issues/255 as it seems both issues relate to having a space in the path. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-15 07:15 UTC
Labels: more-information-needed
