### ISSUE TITLE
Fuzzy finder does not update without window refresh

### ISSUE THREAD

**Issue by alexbuzzbee** [atom/fuzzy-finder#119] opened 2015-07-10 19:58 UTC
After opening a project and creating several new files, pressing cmd+t and typing the name of a file in my project fails to find the file. After ctrl+option+cmd+L (window:reload), the files are found. Unfortunately, I'm not 100% sure what causes the bug, so I can't reproduce for screenshots + steps...

**Comment by gibsjose** [comment] 2015-09-08 14:32
+1

**Comment by mnquintana** [comment] 2015-09-08 16:26
This looks like a duplicate of https://github.com/atom/fuzzy-finder/issues/30 - closing out in favor of that issue. Let me know if I'm misunderstanding though!

**Closed by mnquintana** 2015-09-08 16:26 UTC
