### ISSUE TITLE
Slow startup for large projects

### ISSUE THREAD

**Issue by antelle** [atom/fuzzy-finder#271] opened 2017-01-17 21:04 UTC
Each time you open a project and bring up fuzzy-finder, it shows 'Indexing...' for several seconds. For large projects it's quite annoying.
Suggested solution: save per-project caches after reindex and load them on startup, delete old caches. I've implemented it [in my fork here](https://github.com/antelle/fuzzy-finder-with-faster-loading/blob/master/lib/project-view.coffee) and can make a pull request, if this idea is welcome.
On my project with ≈50k files, fuzzy finder can be used immediately after startup and it saves time.

**Comment by 50Wliu** [comment] 2017-01-17 23:13
It definitely seems feasible.  A PR would be nice, though I can't guarantee that we'll end up going with that solution in the end.

**Comment by eeejay** [comment] 2017-06-01 04:02
I hack on the Gecko, and there are almost 200k files in the source tree. It takes fuzzy finder 17 seconds to index the project. That would be bad enough if it did it the first time you opened it, but it also does it every time you use the finder after refocusing the window.

I made a few changes (pull #301) to optimize how the project gets indexed. There is a 40x speedup, now the Gecko tree gets indexed in half a second.

Caching would be a good idea too, or at least incremental re-indexing.

**Comment by jamesona** [comment] 2017-07-03 16:51
This would be HUGE for myself, and my team. Our company handles a lot of very wide repos, and the sum of the projects fuzzy-finder tries to index ends up being right around 1M inodes.

**Comment by arielnoname** [comment] 2018-01-09 21:14
anything on this? keeps happening. even with small projects

**Comment by alxtz** [comment] 2018-02-02 08:04
@arielnoname if you have file-icon installed, checkout this issue for the root cause https://github.com/atom/fuzzy-finder/issues/269

**Comment by mzhaase** [comment] 2018-07-24 08:56
Is there any progress on this? Happens even without file-icon. Some cache option would be nice.

**Comment by rafeca** [comment] 2019-03-15 09:07
Hey folks, this will get substantially improved by https://github.com/atom/fuzzy-finder/pull/369

**Comment by rafeca** [comment] 2019-03-19 11:37
Now that https://github.com/atom/fuzzy-finder/pull/369 got merged, it's time to close this issue 😄

**Closed by rafeca** 2019-03-19 11:37 UTC
Labels: FY2019Q5 atom perf, performance, startup-time
