### ISSUE TITLE
Suggestion: having the command to ignore Exclude VCS Ignored Paths Setting

### ISSUE THREAD

**Issue by davesnx** [atom/fuzzy-finder#219] opened 2016-05-26 08:31 UTC
Hi guys,
Really awesome work on this I really love it, I have a suggestion, I would like to receive some feedback before go on with this:

I see useful search sometimes inside the ignore packages that `.gitignore` define or any VCS.
Such as, `node_modules` or even `.env` variables are the most common cases. 

I'm thinking like create a command that run the search ignoring the general setting and bindit with a new keymap like `cmd+shift+p+i` or whatever (that's not important here!)

What do you thing guys? It's only my problem? Do you think is usefull? Is it possible to implement(?)

**Comment by 50Wliu** [comment] 2016-05-26 13:45
This is a duplicate of #148 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-26 13:45 UTC
