### ISSUE TITLE
Indexing Project..0

### ISSUE THREAD

**Issue by Postem1** [atom/fuzzy-finder#226] opened 2016-06-30 03:20 UTC
Whenever I start the Fuzzy Finder, it gives a screen stating:  Indexing project..0.

How do I get it to work properly?

**Comment by Ben3eeE** [comment] 2016-07-07 07:27
https://github.com/atom/fuzzy-finder/issues/205?

**Comment by sunnyvempati** [comment] 2016-07-12 19:27
+1

**Comment by 50Wliu** [comment] 2016-07-15 00:48
Closing as a duplicate of #205 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-15 00:48 UTC
