### ISSUE TITLE
Constantly increasing CPU and memory usage after opening a directory with Atom

### ISSUE THREAD

**Issue by sagarpanchal** [atom/fuzzy-finder#216] opened 2016-05-18 18:23 UTC
(Edit: `/var/www/html/` contains **a soft/symbolic link to its parent directory** that causes **recursive directory tree**. After I deleted the soft link, atom is working fine.)

**Reproduction:**
1. Close every Atom window, if running.
2. Open a directory with atom by running  `atom /path/to/directory/`.  In my case `atom /var/www/html/data/`. It doesn't happen with other directories!

**Expected behavior:**
Atom should open with `/var/www/html/data/` opened in tree-view.

**Observed behavior:** (See Screenshots)
Atom opens with `/var/www/html/data/` opened in tree-view.
CPU and memory usage gets high.
And if i don't close project folder in tree-view, it occupies all memory and leads to frozen system.
But, if I close project folder in tree-view before it occupies all the memory, CPU and memory usage gets low and atom runs normally.

**Screenshots**
Opening with nautilus file manager or by running `atom /var/www/html/data/` in gnome-terminal
![1-opening](https://cloud.githubusercontent.com/assets/6555461/15369441/391f5246-1d50-11e6-9a82-1ce8828bb309.png)

Opens Following window
![2-opened](https://cloud.githubusercontent.com/assets/6555461/15369443/3cff19c8-1d50-11e6-8a38-7b6d120eace3.png)

Ran for a minute with constantly increasing CPU and memory usage, system started becoming slow, I also left it for more than 3 minutes with this condition to confirm this issue and my system gets unresponsive/frozen. Tested it more than once and it occurs every time.
![3-memory-and-cpu](https://cloud.githubusercontent.com/assets/6555461/15369445/42ae1e64-1d50-11e6-84ab-497b348c95e3.png)
![4-memory-and-cpu](https://cloud.githubusercontent.com/assets/6555461/15369451/47bb13a8-1d50-11e6-8771-eba5ffb9b15d.png)

After closing Atom
![5-memory-and-cpu-after-closing](https://cloud.githubusercontent.com/assets/6555461/15369454/491d47ac-1d50-11e6-9cd6-09f9a7b4e2b1.png)

**Solution**
I disabled fuzzy-finder package, and issue is gone.

**Installed packages:**
linter
linter-php
minimap
tool-bar
tool-bar-main

**Additional information:**

```
$ atom --version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```
```
$ uname -r
4.4.0-22-generic
```

* Problem can be reproduced in safe mode: [Yes]
* Problem started happening recently, didn't happen in an older version of Atom: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No]

**Comment by 50Wliu** [comment] 2016-05-18 20:06
@sagarpanchal Can you please try the latest Atom 1.8.0 beta and see if that fixes your issue?

**Comment by sagarpanchal** [comment] 2016-05-19 08:48
@50Wliu Yes

**Comment by sagarpanchal** [comment] 2016-05-19 11:14
@50Wliu I can reproduce same issue with atom-beta [https://github.com/atom/atom/releases/download/v1.8.0-beta3/atom-amd64.deb] with `fuzzy-finder` package enabled.

And I can also solve it by disabling `fuzzy-finder` package.

```
$ atom-beta --version
Atom    : 1.8.0-beta3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by sagarpanchal** [comment] 2016-05-19 11:16
@50Wliu I can reproduce same issue with atom-beta [https://github.com/atom/atom/releases/download/v1.8.0-beta3/atom-amd64.deb] with `fuzzy-finder` package enabled.

```
$ atom-beta --version
Atom    : 1.8.0-beta3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by lee-dohm** [comment] 2016-05-24 05:01
Can you give an example of a publicly accessible directory where we can reproduce this problem? What is unique about your `/var/www/html/data` directory that causes the problem?

**Comment by sagarpanchal** [comment] 2016-06-04 14:07
@lee-dohm output of `tree /var/www/html/data/`
```
/var/www/html/data/
├── about.html
├── config
│   ├── color.conf.php
│   └── server.conf.php
├── cookie-manager.php
├── error.php
├── favicon.ico
├── filelinker-main.php
├── filelinker-router.php
├── images
│   ├── bg
│   │   ├── Blue.png
│   │   ├── checkbox-checked.svg
│   │   ├── checkbox-unchecked.svg
│   │   ├── Custom.png
│   │   ├── Gray.png
│   │   ├── Green.png
│   │   └── Orange.png
│   ├── checkbox-checked.svg
│   ├── checkbox-unchecked.svg
│   ├── go-home.svg
│   ├── go-previous.svg
│   └── icons
│       ├── css.png
│       ├── file.png
│       ├── folder.png
│       ├── image.png
│       ├── office.png
│       ├── php.png
│       ├── script.png
│       ├── sound.png
│       ├── video.png
│       ├── word.png
│       ├── xml.png
│       └── zip.png
├── menu.php
├── redir.php
├── scripts
│   ├── jquery.min.js
│   ├── list.min.js
│   ├── menu.js
│   ├── search.js
│   └── sorttable.js
├── styles
│   ├── animate.css
│   ├── color_converter.php
│   ├── colors.php
│   ├── css.php
│   ├── FiraCode.otf
│   ├── menu_css.php
│   ├── normalize.css
│   ├── tooltip_css.php
│   └── Ubuntu.ttf
└── tree.txt

6 directories, 48 files
```

**Comment by sagarpanchal** [comment] 2016-06-04 14:13
```
/var/www/html/data$ du -ha
4.0K	./about.html
8.0K	./error.php
4.0K	./menu.php
4.0K	./redir.php
8.0K	./styles/css.php
4.0K	./styles/color_converter.php
4.0K	./styles/tooltip_css.php
8.0K	./styles/menu_css.php
4.0K	./styles/colors.php
8.0K	./styles/normalize.css
76K	    ./styles/animate.css
148K	./styles/FiraCode.otf
348K	./styles/Ubuntu.ttf
612K	./styles
4.0K	./images/go-home.svg
4.0K	./images/go-previous.svg
40K	    ./images/bg/Blue.png
32K	    ./images/bg/Custom.png
48K	    ./images/bg/Green.png
4.0K	./images/bg/checkbox-unchecked.svg
4.0K	./images/bg/checkbox-checked.svg
44K	    ./images/bg/Gray.png
44K	    ./images/bg/Orange.png
220K	./images/bg
4.0K	./images/checkbox-unchecked.svg
4.0K	./images/checkbox-checked.svg
4.0K	./images/icons/sound.png
4.0K	./images/icons/file.png
4.0K	./images/icons/xml.png
4.0K	./images/icons/word.png
4.0K	./images/icons/office.png
4.0K	./images/icons/folder.png
4.0K	./images/icons/php.png
4.0K	./images/icons/video.png
4.0K	./images/icons/image.png
4.0K	./images/icons/css.png
4.0K	./images/icons/zip.png
4.0K	./images/icons/script.png
52K	    ./images/icons
292K	./images
20K	    ./scripts/sorttable.js
136K	./scripts/jquery.min.js
4.0K	./scripts/menu.js
4.0K	./scripts/search.js
28K	    ./scripts/list.min.js
196K	./scripts
4.0K	./filelinker-router.php
24K	    ./favicon.ico
4.0K	./cookie-manager.php
12K 	./filelinker-main.php
4.0K	./config/server.conf.php
4.0K	./config/color.conf.php
12K	    ./config
1.2M	.
```

**Comment by sagarpanchal** [comment] 2016-06-04 15:20
@lee-dohm 
I tested the copy of `/var/www/html/data` and found a **symbolic link to (parent directory)** `/var/www/html/` that must be causing the issue.
I deleted the symbolic link to parent directory and relaunched atom and everything worked fine.

**Comment by lee-dohm** [comment] 2016-06-07 16:32
Ah, thank you @sagarpanchal. I'm pretty sure this is a dupe then of another Issue. I'll track it down tomorrow.

**Comment by lee-dohm** [comment] 2016-06-09 17:35
This is a duplicate of https://github.com/atom/atom/issues/10286. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-06-09 17:35 UTC
Labels: more-information-needed, performance
