### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat 'C:/Windows\System32\inetsrv\config'

### ISSUE THREAD

**Issue by hgon23** [atom/fuzzy-finder#302] opened 2017-06-11 13:53 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.8

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'C:\Windows\System32\inetsrv\config'

```
At fs.js:982

Error: EPERM: operation not permitted, lstat 'C:\Windows\System32\inetsrv\config'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Proxy.realpathSync (fs.js:1657:19)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:21:1
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:19:1)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/fuzzy-finder/lib/main.js:119:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/fuzzy-finder/lib/main.js:33:1
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:07.6.0 find-and-replace:show (input.hidden-input)
     -2:03.7.0 core:confirm (input.hidden-input)
     -1:49.6.0 find-and-replace:show (input.hidden-input)
     -1:49.3.0 core:paste (input.hidden-input)
     -1:48.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 0.4.1 
pigments 0.26.0 
```

**Comment by rsese** [comment] 2017-06-12 18:07
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/289. You may want to subscribe there for updates.  Feel free to comment there and let us know if the error is reproducible and if it's reproducible in safe mode (`atom --safe`).   Steps to reproduce would be helpful as well.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-12 18:07 UTC
