### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by benogle** [atom/fuzzy-finder#64] opened 2014-12-11 17:00 UTC
_From @lagora on December 11, 2014 15:40_

Uncaught TypeError: undefined is not a function

**Atom Version**: 0.154.0
**System**: Mac OS X 10.9.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:118

TypeError: undefined is not a function
  at ProjectView.module.exports.FuzzyFinderView.openPath (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:118:50)
  at ProjectView.module.exports.FuzzyFinderView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:200:21)
  at ProjectView.module.exports.FuzzyFinderView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:178:19)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/select-list-view.js:113:24)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

_Copied from original issue: atom/atom#4549_

**Comment by xdumaine** [comment] 2015-01-05 16:23
This happens to me every single time, the first time I use fuzzy finder after launching atom. I always launch atom via terminal.

**Comment by ajclarke90** [comment] 2015-01-07 11:46
I can confirm I am also getting this error. 

Atom Version: 0.166.0 
OS X Mavericks V 10.10.1

Fuzzy finder seemed to be working fine yesterday, though I don't recall making any changes or updating anything since then.

**Comment by kevinsawicki** [comment] 2015-01-07 17:42
@xdumaine @ajclarke90 is it happening when you open a specific file or any file?

Does it happen if you quit Atom and launch it in safe mode (`atom --safe`)?

**Comment by ajclarke90** [comment] 2015-01-08 10:02
I happen to be opening a directory containing all my code. Atom successfully opens the last .f90 file I had open at the time I closed it, and then I can't use fuzzy finder to navigate to other files in the project.

I can confirm this also happens if I launch atom from the command line in safe mode. I have also tried manually launching the GUI and then opening the project, and opening the project from the command line. All of these give the above error.

**Comment by ajclarke90** [comment] 2015-01-08 10:50
Hey folks, I think I have narrowed it down. Uninstalling the build package appears to have fixed my fuzzy finder functionality. 

This is odd though, because from what I understood, safe mode should disable all packages. However, uninstalling and reinstalling build, has given me fizzy finder functionality back again. 

This also fixed tree-view for me: https://github.com/atom/tree-view/issues/314

**Comment by xdumaine** [comment] 2015-01-08 18:36
@ajclarke90 I don't have a package "build" to uninstall.

**Comment by maxbrunsfeld** [comment] 2015-02-26 01:23
@xdumaine it sounds like some package you have installed is causing this. Does this happen if upgrade to the latest Atom and run `atom --safe`?

**Comment by xdumaine** [comment] 2015-02-26 13:30
I actually haven't seen this lately. Recent updates must have resolved it, at least for me.

**Comment by 50Wliu** [comment] 2018-02-18 05:23
Probably has been resolved.

**Closed by 50Wliu** 2018-02-18 05:23 UTC
Labels: bug, more-information-needed, uncaught-exception
