### ISSUE TITLE
Keeping Fuzzy finder search field active when switching focus away from Atom

### ISSUE THREAD

**Issue by aev1tas** [atom/fuzzy-finder#121] opened 2015-07-14 17:55 UTC
Hi,

would it be possible to implement a menu option, that keeps the command pallete and fuzzy finder windows open and available even after having switched apps on Mac. For example, start typing in the finder, switch to firefox to look something up, switch back to Atom and the fuzzy finder is still opened and has preserved your search.

Kind Regards,
aev1tas

**Comment by 50Wliu** [comment] 2015-07-14 23:43
Hey @aev1tas, this looks like it's a duplicate of atom/atom#1918 - could you subscribe there instead?  Thanks.

**Closed by 50Wliu** 2015-07-14 23:43 UTC
